name: booking_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.22.0
  intl: 0.17.0
  cloud_firestore: 3.4.7
  syncfusion_flutter_calendar: 20.2.48
  google_fonts: 3.0.1
  flutter_svg: 1.1.4
  flutter_form_builder: 7.6.0
  form_builder_validators: 8.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

